### ISSUE TITLE
Use Twitter's new Ads API v7

### ISSUE THREAD

**Issue by gr2m** [gr2m/twitter-together#108]
**What’s missing?**

Twitter released a new version of it's ads.twitter.com API (v7):
https://twittercommunity.com/t/ads-api-version-7/135093

**Why?**

v6 will stop working on Sep 1st, 2020

**Comment by Andrew-Chen-Wang** [comment]
@gr2m Was the breaking change the tokens given? I created a new twitter dev account and the keys given were: API Key, Secret Key, and Bearer Token. That's not 4 keys? Looking to publish tweets, so I just found this problem.

**Comment by gr2m** [comment]
I really don't know, I'm not familiar with Twitter's APIs. I'd appreciate help with upgrading `twitter-together` to utilize the new APIs

**Comment by Andrew-Chen-Wang** [comment]
No problem, looking into it.

**Comment by Jolg42** [comment]
For reference:

Twitter Ads API roadmap:
https://developer.twitter.com/en/docs/twitter-ads-api/versioning

Version | Path | Introduction Date | Deprecated Date | End of Life Date
-- | -- | -- | -- | --
9.0 | /9/ | March 2, 2021 | August 31, 2021 |  
8.0 | /8/ | September 8, 2020 | March 2, 2021 | August 31, 2021
7.0 | /7/ | March 3, 2020 | September 1, 2020 | March 2, 2021

Changes
https://twittercommunity.com/t/ads-api-version-8/141914

It looks like nothing needs to be updated 🤷‍♂️

**Comment by Jolg42** [comment]
That should do it https://github.com/gr2m/twitter-together/pull/126 😃

**Comment by Andrew-Chen-Wang** [comment]
I'm confused; isn't twitter-together using API v6 which reached end of life on Sep 1? If this has nothing to do with the number of tokens, then I guess I can open a new issue about why Twitter API devs only get three tokens now (and twitter-together accepts 4 different tokens).

Twitter-together isn't crashing but Tweeting results in an authentication failed. Perhaps I filled out the env secrets  incorrectly?

**Comment by gr2m** [comment]
I guess it would make sense to upgrade to v8 if it's already available?

**Comment by Jolg42** [comment]
Indeed version 8 sounds better!

**Comment by Jolg42** [comment]
Here we go https://github.com/gr2m/twitter-together/pull/128

And it only affects Tweets with a poll so you can schedule one if you want to verify 😃

**Comment by Andrew-Chen-Wang** [comment]
Question @gr2m what are your GitHub secrets names? I've only got three because I was given 3 tokens on Twitter dev sign up: API Key, API Secret Key, and an Auth Bearer Token. Just wondering since I just saw you create a .tweet file as a test.
