### ISSUE TITLE
I LOVE IT ❤️

### ISSUE THREAD

**Issue by horacioh** [gr2m/twitter-together#113]
**How do you use twitter-together?**

I'm planning on using Twitter-together with my @aprendegatsbyjs account, so all the coaches CAN tweet on it without giving them the credentials

**What do you love about it?**

That IT JUST WORKED!! https://twitter.com/aprendegatsbyjs/status/1242248525494222849

**How did you learn about it?**

someone shared the repo link from twitter :)

**Comment by gr2m** [comment]
Glad you like it! Thank you for the kind words :)
