### ISSUE TITLE
Use `tweet-characters-left` for more validation

### ISSUE THREAD

**Issue by JasonEtco** [gr2m/twitter-together#50]
**What’s missing?**

Correct me if I'm wrong, but we don't currently validate new tweets for their length. It'd be great to do that and `exit 1` if the length of a tweet is too long. Here's a handy package I found for doing that: [mscoutermarsh/tweet-characters-left](https://github.com/mscoutermarsh/tweet-characters-left).

It uses the [twitter-text](https://github.com/twitter/twitter-text) library to get an accurate length and returns a comparison.

**Comment by gr2m** [comment]
Yes it does: https://github.com/gr2m/twitter-together/blob/master/test/pull-request-invalid-tweet/test.js

I use the  `twitter-text` package directly right now. I parse tweets here:

https://github.com/gr2m/twitter-together/blob/c3f45ae48d473c83fbff66e7518e299b3b14068d/lib/pull-request/get-new-tweets.js#L42

Then check if all tweets are valid when creating the check run:
https://github.com/gr2m/twitter-together/blob/c3f45ae48d473c83fbff66e7518e299b3b14068d/lib/pull-request/create-check-run.js#L7

And try to give helpful error messages at https://github.com/gr2m/twitter-together/blob/c3f45ae48d473c83fbff66e7518e299b3b14068d/lib/pull-request/create-check-run.js#L23-L38

**Comment by JasonEtco** [comment]
Oh, my bad! Somehow missed this, thanks for pointing it out.
