### ISSUE TITLE
Setup instruction notes

### ISSUE THREAD

**Issue by JasonEtco** [gr2m/twitter-together#51]
Just two tiny things:

**What happened?**

Cannot use `twitter-together` as the app name:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/10660468/54074848-b65a1d80-4265-11e9-866f-4813ee20147e.png">

Setup PR didn't open, I had used the wrong secret names - my mistake, but the `+` is what I did and was expecting:

```diff
- TWITTER_API_KEY_SECRET
+ TWITTER_API_SECRET

- TWITTER_ACCESS_TOKEN_SECRET
+ TWITTER_ACCESS_SECRET
```

<img width="735" alt="image" src="https://user-images.githubusercontent.com/10660468/54074887-3d0efa80-4266-11e9-9c27-09c8150a47e0.png">

**Comment by gr2m** [comment]
Hmm the right keys are

```js
const twitter = new Twitter({
  consumer_key: TWITTER_API_KEY,
  consumer_secret: TWITTER_API_SECRET_KEY,
  access_token_key: TWITTER_ACCESS_TOKEN,
  access_token_secret: TWITTER_ACCESS_TOKEN_SECRET
})
```

I changed them at some point to better align with how twitter names them.

Where did you find `TWITTER_API_KEY_SECRET`? I don’t see it in the code? An neither `TWITTER_API_SECRET` nor `TWITTER_ACCESS_SECRET` should ave worked if you followed the instructions, or I miss something

**Comment by gr2m** [comment]
> Cannot use `twitter-together` as the app name:

what do you think about this change?

```diff
- ### App name (required)
- 
- `twitter-together-<your twitter account name>`
+ ### App name (required)
+ 
+ `twitter-together-<your twitter account name>`
```

**Comment by JasonEtco** [comment]
> Where did you find TWITTER_API_KEY_SECRET? I don’t see it in the code? An neither TWITTER_API_SECRET nor TWITTER_ACCESS_SECRET should ave worked if you followed the instructions, or I miss something

I didn't - I just assumed that's what they'd be based on my experience writing these out 🤷‍♂️ I fully realize its wrong, the naming just confused me.

> what do you think about this change?

Makes sense to me - I named ours `probot-twitter-together`, but before/after doesn't make a big deal.

**Comment by gr2m** [comment]
fixed via https://github.com/gr2m/twitter-together/commit/c3f45ae48d473c83fbff66e7518e299b3b14068d
