### ISSUE TITLE
🧚‍♂️ Mastodon?

### ISSUE THREAD

**Issue by ccoenen** [gr2m/twitter-together#61]
**What’s missing?**
[Mastodon](https://github.com/tootsuite/mastodon/) support!

**Why?**
Mastodon is a nice place for open source projects. It shares many of the properties of twitter, but is open source and decentralised itself.

**Alternatives you tried**
I did not try any alternatives, mostly because I know your software is awesome and other's is not always awesome.

**Comment by gr2m** [comment]
👋 Hi Claudius!

I’m not familiar with Mastadon’s APIs. Do you think it would be confusing to add Mastadon support to `twitter-together`? Maybe we should either rename if we add Mastadon support, or create a sibling project: `mastadon-together`?

**Comment by ccoenen** [comment]
In my opinion that would depend on the amount of change required. If this were done with switching out one library for another and having one more config (instance, perhaps) then I wouldn't duplicate it.

To be honest, I didn't really look into mastodon API so far. If I am allowed to suggest a dorky name in case of a fork: "tootgether" 🤓️ (tweets are called Toots on Mastodon).

**Comment by gr2m** [comment]
lol "tootgether" is awesome 😂

I’ll leave the open issue, maybe someone wants to investigate

**Comment by JasonEtco** [comment]
This sounds cool! But I would definitely suggest that it be in another repo, potentially a fork of this one. Actions get a lot from being in focused repositories (like indexing, searching, marketplace-listing). Plus, I don't think `twitter-together` needs to be the be-all-end-all for social-media-ing via GitHub, having it scoped to just Twitter helps keep it clean. Just my $0.02 though 😊

**Comment by gr2m** [comment]
I agree with what @JasonEtco says, Mastadon is out of scope for this project

**Comment by gr2m** [comment]
Check out https://github.com/joschi/toot-together/ by @joschi!

**Comment by ccoenen** [comment]
wow that's so cool! :-)
Thanks for mentioning it!
